### ISSUE TITLE
Error after initial set up on product pages

### ISSUE THREAD

**Issue by webmavenio** [perryraskin/nextjs-tailwind-shopify-storefront#3]
Receiving:
`Unexpected token < in JSON at position 0`
Storefront Key and URI both correct
I haven't looked too deep into it yet, but I'm not sure if this is just on my end.

**Comment by JaviEzpeleta** [comment]
I'm having the same problem too :(

**Comment by perryraskin** [comment]
I'm so sorry, I'm not sure how I didn't see these! Will take a look later!! :)

**Comment by perryraskin** [comment]
Ok, i updated packages, everything seemed to work for me. Please let me know if any of you still have this issue! Will close this for now.

**Comment by zevonjunior** [comment]
I'm still getting the 
Unexpected token < in JSON at position 0
error.

Just to confirm: the store uri would be something like "https://teststore.myshopify.com/api/graphql".

**Comment by perryraskin** [comment]
Yes, that's correct! Super weird. It works just fine for me.

Maybe try using `NEXT_PUBLIC_` instead of `REACT_APP_` for the environment variables? I believe it was changed for newer versions of Next.js. See this post https://nextjs.org/docs/basic-features/environment-variables

**Comment by zevonjunior** [comment]
Thanks for the very quick reply! 
I will try your suggestion and report back (tomorrow).
Thank again!
